dataset: Birth

source_columns:

  date_of_birth:
    aliases:
      - "Date of Birth (dd-mm-yy)"
    datatype: date
    required: true
    output: true

  sex:
    aliases:
      - "Sex"
      - "Sex (Indicate whether male or female)"
    datatype: string
    required: true
    output: true
    valid_values:
      male: Male
      m: Male
      female: Female
      f: Female

  nature_of_birth:
    aliases:
    - "Nature of Birth"
    - "Nature of birth"
    - "Nature of birth (Indicate whether born alive or dead)"
    datatype: string
    required: true
    output: true
    valid_values:
      alive: "Born Alive"
      born alive: "Born Alive"
      dead: "Born Dead"
      born dead: "Born Dead"

  birth_weight:
    datatype: float
    required: true

    aliases:
      - "Weight of birth(Kgs)"
    minimum: 0.3
    maximum: 8.0
    output: true

  place_of_birth:
    aliases:
      - "Place of Birth"
      - "Place of birth"
      - "Place of birth (Indicate the name of facility or Sublocation of birth)"
    datatype: string
    required: true
    output: true
  
  place_type:
    datatype: string
    required: true

    aliases:
      - "Type of place"
      - "Type of place(Indicate whether Home or Health Facility)"

    valid_values:
      home: Home
      health facility: Health Facility

  mother_age:
    aliases:
      - "Age of Mother"
      - "Age of the Mother"
      - "Age of the mother(indicate the age of the mother at the birth of the child)"
    datatype: integer
    required: true
    minimum: 13
    maximum: 55
    output: true

  marital_status:
    datatype: string
    required: true

    aliases:
      - "Marital status"

    valid_values:
      single: Single
      married: Married
      divorced: Divorced
      separated: Separated
      widowed: Widowed
      not stated: Not stated

  nationality:
    datatype: string
    required: true

    aliases:
      - "Nationality of the mother"

    valid_values:
      kenyan: Kenyan
      ugandan: Ugandan
      tanzanian: Tanzanian
      rwandan: Rwandan
      burundian: Burundian
      south sudanese: South Sudanese
      ethiopian: Ethiopian
      somali: Somali
      other: Other

  occupation:
    datatype: string
    required: true

    aliases:
      - "Ocupation of the mother"
      - "Occupation of the mother"

  education:
    datatype: string
    required: true

    aliases:
      - "Mother's level of Education"
      - "Education level of the mother"

    valid_values:
      primary: Primary
      secondary: Secondary
      tertiary: Tertiary
      university: University
      not stated: Not stated
      never studied: Never Studied


  residence:
    datatype: string
    required: true
    aliases:
      - "Place of Residence"
      - "Place of Residence(Sub County)"
      - "Place of Residence (Sub County)"
      - "Place of Residence (indicate the sub county where the mother residence)"


  registration_date:
    datatype: date
    required: true

    aliases:
      - "Date of Registration"
      - "Date of Registration (dd-mm-yy)"
      - "Date of Registration(dd-mm-yy)"

  entry_number:
    datatype: string
    required: true

    aliases:
      - "Entry Number"

derived_columns:

  status:
    aliases:
      - "Status"
      - T.O.R
      - tor
      - TOR
      - T O R
      - Time of Registration
    datatype: string
    required: true
  Valid values:
      current: Current
      Late: Late

output_columns:

  - date_of_birth
  - sex
  - nature_of_birth
  - birth_weight
  - place_of_birth
  - place_type
  - mother_age
  - marital_status
  - nationality
  - occupation
  - education
  - residence
  - registration_date
  - entry_number
  - status