dataset: death

source_columns:

  deceased_name:
    datatype: string
    required: true
    aliases:
      - Name of Deceased
      - Name of deceased
      - Deceased Name
      - Full Name of Deceased
      - Name of Deceased (Indicate full names of the deceased)

  id_number:
    datatype: string
    required: true
    aliases:
      - ID Number
      - ID Number(Indicate the ID number where applicable and available)
      - ID No
      - Identification Number
      - National ID

  date_of_death:
    datatype: date
    required: true
    aliases:
      - Date of Death
      - DOD
      - Death Date

  sex:
    aliases:
      - "Sex"
      - "Sex (Indicate whether male or female)"
      - Gender
    datatype: string
    required: true
    output: true
    valid_values:
      male: Male
      m: Male
      female: Female
      f: Female

  age:
    datatype: integer
    required: true
    minimum: 0
    maximum: 130
    aliases:
      - "Age(indicate number eg 1,2,3,)"
      - Age

  age_unit:
    datatype: string
    required: true
    aliases:
      - "unit of age(days,months or years)"
      - Unit of age
      - Age Unit
    valid_values:
      days: Days
      months: Months
      years: Years

  place_of_death:
    datatype: string
    required: true
    aliases:
      - "Place of death(Indicate the name of exact place of death)"
      - Place of death
      - Place of Death

  marital_status:
    datatype: string
    required: true
    aliases:
      - "MARITAL STATUS"
    valid_values:
      single: "Single"
      married: "Married"
      divorced: "Divorced"
      widowed: "Widowed"
      not stated: "Not Stated"

  place_type:
    datatype: string
    required: true
    aliases:
      - Type of place(Indicate whether Home or Health Institution)
      - "Type of place(Indicate whether Home or Health Institution)"
      - Type of place
      - Place Type
    valid_values:
      home: "Home"
      health institution: "Health Institution"

  residence:
    datatype: string
    required: true
    aliases:
      - Place of usual residence
      - Place of usual residence(SUB-COUNTY)

  cause_of_death:
    datatype: string
    required: true
    aliases:
      - Cause of death(Indicate the underlying cause of death)
      - Cause of death

  death_certification:
    datatype: string
    required: true
    aliases:
      - CAUSE OF DEATH CERTIFICATION(State whether medically certified or lay reporting)
      - Cause of death certification(state whether medically certified or lay reporting)
      - Cause of death certification
      - Death Certification
    valid_values:
      medically certified: "Medically Certified"
      lay reporting: "Lay Reporting"

  registration_date:
    datatype: date
    required: true
    aliases:
      - "Date of Registration(dd-mm-yy)"

  entry_number:
    datatype: string
    required: true
    aliases:
      - "Entry Number"
derived_columns:
  status:
    datatype: string
    required: true
    aliases:
      - "Status"
      - T.O.R
      - tor
      - TOR
      - T O R
      - Time of Registration
    valid_values:
      current: "Current"
      late: "Late"